In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
from pathlib import Path

# Ejercicio 1

## 1.

In [2]:
cwd = Path.cwd()
#crea en path relativo de donde esta el csv
filename = os.path.join(cwd, "Fitness_trackers.csv") 
data_df = pd.read_csv(filename)

data_df.head(n=20)

,Brand Name,Device Type,Model Name,Color,Selling Price,Original Price,Display,Rating (Out of 5),Strap Material,Average Battery Life (in days),Reviews
0,Xiaomi,FitnessBand,Smart Band 5,Black,"2,499","2,999",AMOLED Display,4.1,Thermoplastic polyurethane,14,NaN
1,Xiaomi,FitnessBand,Smart Band 4,Black,"2,099","2,499",AMOLED Display,4.2,Thermoplastic polyurethane,14,NaN
2,Xiaomi,FitnessBand,HMSH01GE,Black,"1,722","2,099",LCD Display,3.5,Leather,14,NaN
3,Xiaomi,FitnessBand,Smart Band 5,Black,"2,469","2,999",AMOLED Display,4.1,Thermoplastic polyurethane,14,NaN
4,Xiaomi,FitnessBand,Band 3,Black,"1,799","2,199",OLED Display,4.3,Plastic,7,NaN
5,Xiaomi,FitnessBand,Band - HRX Edition,Black,"1,299","1,799",OLED Display,4.2,Plastic,20,NaN
6,Xiaomi,FitnessBand,Band 2,Black,"2,499","2,499",OLED Display,4.3,Plastic,7,NaN
7,Xiaomi,Smartwatch,Revolve,Black,"12,349","15,999",AMOLED Display,4.4,Silicone,14,2
8,Xiaomi,Smartwatch,RevolveActive,Black,"12,999","15,999",AMOLED Display,4.4,Silicone,14,3
9,Xiaomi,FitnessBand,Smart Band 3i,Black,"1,270","1,599",OLED Display,4.2,Thermoplastic polyurethane,7,NaN
10,OnePlus,FitnessBand,Steven Harrington Edition Band,Blue,"3,299","3,999",AMOLED Display,4.3,Thermoplastic polyurethane,7,NaN
11,OnePlus,FitnessBand,Band,Dual Color,"2,499","2,799",AMOLED Display,4.2,Thermoplastic polyurethane,7,NaN
12,FitBit,Smartwatch,Versa 2,"Grey, Pink, Black","11,999","14,999",AMOLED Display,4.3,Silicone,7,NaN
13,FitBit,Smartwatch,Sense,"Black, Pink, Beige","21,499","22,999",AMOLED Display,4.2,Elastomer,7,NaN
14,FitBit,Smartwatch,Versa 3,"Black, Blue, Pink","17,999","18,999",AMOLED Display,4.3,Elastomer,7,NaN
15,FitBit,FitnessBand,Charge 4,"Storm Blue, Black, Rosewood","9,999","9,999",PMOLED Display,4.2,Elastomer,7,NaN
16,FitBit,FitnessBand,Inspire,Maroon,"7,990","7,999",LED Display,4.2,Silicone,5,NaN
17,FitBit,FitnessBand,Inspire 2,"Black, Desert Rose, Lunar White","6,999","7,999",PMOLED Display,4.4,Thermoplastic polyurethane,10,NaN
18,FitBit,FitnessBand,Lunar,White,"10,899","10,999",AMOLED Display,4.7,Silicone,7,NaN
19,FitBit,FitnessBand,Charge 4,Granite Reflective,"10,999","11,999",PMOLED Display,4.2,Elastomer,7,NaN

In [3]:
print('Cantidad de Filas y columnas:',data_df.shape)
print('Nombre columnas:',data_df.columns)

Cantidad de Filas y columnas: (565, 11)
Nombre columnas: Index(['Brand Name', 'Device Type', 'Model Name', 'Color', 'Selling Price',
       'Original Price', 'Display', 'Rating (Out of 5)', 'Strap Material',
       'Average Battery Life (in days)', 'Reviews'],
      dtype='object')

Ejercicio 1

In [4]:
#Número de muestras (valores distintos de missing)
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565 entries, 0 to 564
Data columns (total 11 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Brand Name                      565 non-null    object
 1   Device Type                     565 non-null    object
 2   Model Name                      565 non-null    object
 3   Color                           565 non-null    object
 4   Selling Price                   565 non-null    object
 5   Original Price                  565 non-null    object
 6   Display                         565 non-null    object
 7   Rating (Out of 5)               514 non-null    float64
 8   Strap Material                  565 non-null    object
 9   Average Battery Life (in days)  565 non-null    int64
 10  Reviews                         78 non-null     object
dtypes: float64(1), int64(1), object(9)
memory usage: 48.7+ KB

In [5]:
#cambio de tipo string a float estas columnas

data_df["Selling Price"]=data_df["Selling Price"].str.replace(',','').astype(float)

data_df["Original Price"]=data_df["Original Price"].str.replace(',','').astype(float)

data_df["Reviews"]=data_df["Reviews"].str.replace(',','').astype(float)

In [6]:
#número de muestras y NAs
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565 entries, 0 to 564
Data columns (total 11 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Brand Name                      565 non-null    object
 1   Device Type                     565 non-null    object
 2   Model Name                      565 non-null    object
 3   Color                           565 non-null    object
 4   Selling Price                   565 non-null    float64
 5   Original Price                  565 non-null    float64
 6   Display                         565 non-null    object
 7   Rating (Out of 5)               514 non-null    float64
 8   Strap Material                  565 non-null    object
 9   Average Battery Life (in days)  565 non-null    int64
 10  Reviews                         78 non-null     float64
dtypes: float64(4), int64(1), object(6)
memory usage: 48.7+ KB

In [8]:
#calculamos los principales estadísticos de las variables numéricas
data_df.describe()

,Selling Price,Original Price,Rating (Out of 5),Average Battery Life (in days),Reviews
count,565.000000,565.000000,514.000000,565.000000,78.000000
mean,22110.373451,25365.361062,4.229961,9.026549,2492.948718
std,19914.926066,20384.028759,0.390827,7.868670,5607.529743
min,1195.000000,1599.000000,2.000000,1.000000,2.000000
25%,8990.000000,12999.000000,4.025000,2.000000,107.750000
50%,15995.000000,19995.000000,4.300000,7.000000,346.000000
75%,29900.000000,32900.000000,4.500000,14.000000,1580.750000
max,122090.000000,122090.000000,5.000000,45.000000,23426.000000

# Ejercicio2